#!/bin/sh -e
# -*- shell-script -*-

##
## Mincer daemon entry point
##

if [ "$1" = "-h" -o "$1" = "--help" -o -z "$1" ]; then
    echo "\
Usage:
   $0 <config-file>\
   $0 <config-file> stop" 1>&2
    exit 1
fi

MINCER_CONFIG=`readlink --canonicalize-missing "$1"`
. "$MINCER_CONFIG"

cd "$ROOT_DIR"

PIDFILE="$ROOT_DIR"/pid
if [ "$2" = "stop" ]; then
    pkill --pidfile "$PIDFILE" --exact inoticoming > /dev/null 2>&1 || :
    exit 0
fi

if pgrep --pidfile "$PIDFILE" --exact inoticoming > /dev/null 2>&1; then
    # The daemon already running.
    exit 0
fi

[ -z "$INCOMING_DIR" ] && INCOMING_DIR="$ROOT_DIR"/incoming
mkdir -p "$INCOMING_DIR"

exec inoticoming --initialsearch \
    --logfile "$ROOT_DIR"/processing.log --pid-file "$PIDFILE" \
    "$INCOMING_DIR" \
    --regexp "$FILENAME_REGEXP" --stdout-to-log --stderr-to-log \
    mincer-worker "$MINCER_CONFIG" '{}' \;
